import { createContext, useCallback, useContext, useEffect, useMemo, useState } from "react";
import { GLOSSARY as BASE_GLOSSARY, buildGlossaryIndex } from "../data/glossary";

// ═══════════════════════════════════════════════════════
//  useEditableGlossary
//  Manages localStorage-persisted glossary edits + additions.
//
//  Storage shape (JSON in localStorage[STORAGE_KEY]):
//    {
//      entryEdits:  { [key]: { cat, abbr, term, def, ex } },
//      newEntries:  [ { cat, abbr, term, def, ex } ],
//      deleted:     [ key, key, ... ]
//    }
//
//  Each base entry's stable "key" is `${origCat}|${origAbbr}|${origTerm}`.
//  This is used to apply edits and mark deletions without relying on array
//  index (so reordering the source file doesn't break anything).
//
//  WARNING: This is a CLIENT-SIDE store only. Edits live in the editor's
//  browser until they hit "Export glossary.js" and the dev pastes the
//  output back into the source file.
// ═══════════════════════════════════════════════════════

const STORAGE_KEY = "bm-lms-glossary-edits";

const GlossaryEditCtx = createContext(null);

export function entryKey(e) {
  return `${e.cat || ""}|${e.abbr || ""}|${e.term || ""}`;
}

function loadEdits() {
  try {
    const raw = JSON.parse(localStorage.getItem(STORAGE_KEY) || "{}");
    return {
      entryEdits: raw.entryEdits || {},
      newEntries: Array.isArray(raw.newEntries) ? raw.newEntries : [],
      deleted: Array.isArray(raw.deleted) ? raw.deleted : [],
    };
  } catch {
    return { entryEdits: {}, newEntries: [], deleted: [] };
  }
}

export function GlossaryProvider({ children }) {
  const [edits, setEdits] = useState(loadEdits);

  // Persist to localStorage
  useEffect(() => {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(edits));
    } catch { /* storage full — silently fail */ }
  }, [edits]);

  // Build the merged effective glossary array
  const glossary = useMemo(() => {
    const baseFiltered = BASE_GLOSSARY
      .filter((e) => !edits.deleted.includes(entryKey(e)))
      .map((e) => {
        const k = entryKey(e);
        const patch = edits.entryEdits[k];
        return patch ? { ...e, ...patch } : e;
      });
    return [...baseFiltered, ...edits.newEntries];
  }, [edits]);

  // Build the index (GMAP + regex) from the merged glossary
  const index = useMemo(() => buildGlossaryIndex(glossary), [glossary]);

  const updateEntry = useCallback((origEntry, patch) => {
    const k = entryKey(origEntry);
    setEdits((prev) => {
      // If origEntry was a brand-new entry, find it in newEntries by reference key
      const isNew = prev.newEntries.some((e) => entryKey(e) === k);
      if (isNew) {
        return {
          ...prev,
          newEntries: prev.newEntries.map((e) => (entryKey(e) === k ? { ...e, ...patch } : e)),
        };
      }
      return {
        ...prev,
        entryEdits: { ...prev.entryEdits, [k]: { ...(prev.entryEdits[k] || {}), ...patch } },
      };
    });
  }, []);

  const addEntry = useCallback((entry) => {
    const cleaned = {
      cat: entry.cat || "B&M GENERAL VOCABULARY",
      abbr: entry.abbr || "",
      term: entry.term || "",
      def: entry.def || "",
      ex: entry.ex || "",
    };
    setEdits((prev) => ({ ...prev, newEntries: [...prev.newEntries, cleaned] }));
  }, []);

  const deleteEntry = useCallback((origEntry) => {
    const k = entryKey(origEntry);
    setEdits((prev) => {
      // If it's a new entry, remove from newEntries
      const isNew = prev.newEntries.some((e) => entryKey(e) === k);
      if (isNew) {
        return { ...prev, newEntries: prev.newEntries.filter((e) => entryKey(e) !== k) };
      }
      // Otherwise mark base entry as deleted
      return {
        ...prev,
        deleted: prev.deleted.includes(k) ? prev.deleted : [...prev.deleted, k],
      };
    });
  }, []);

  const resetGlossary = useCallback(() => {
    setEdits({ entryEdits: {}, newEntries: [], deleted: [] });
  }, []);

  const editCount = useMemo(() => {
    return (
      Object.keys(edits.entryEdits).length +
      edits.newEntries.length +
      edits.deleted.length
    );
  }, [edits]);
  const hasEdits = editCount > 0;

  // Export the merged glossary as a drop-in src/data/glossary.js replacement.
  // The dev can download, paste in, and the changes become permanent.
  const exportGlossary = useCallback(() => {
    const escape = (s) =>
      String(s ?? "")
        .replace(/\\/g, "\\\\")
        .replace(/"/g, '\\"')
        .replace(/\n/g, "\\n");
    const lines = glossary.map(
      (e) =>
        `  {cat:"${escape(e.cat)}",abbr:"${escape(e.abbr)}",term:"${escape(e.term)}",def:"${escape(e.def)}",ex:"${escape(e.ex)}"},`
    );
    const fileContent =
      `// Auto-generated by Edit Mode — ${new Date().toISOString()}\n` +
      `// Replace the GLOSSARY array in src/data/glossary.js with this block to make edits permanent.\n` +
      `export const GLOSSARY = [\n${lines.join("\n")}\n];\n`;
    const blob = new Blob([fileContent], { type: "text/javascript" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = "glossary.js";
    a.click();
    URL.revokeObjectURL(url);
  }, [glossary]);

  const value = {
    glossary,
    GMAP: index.GMAP,
    GREGEX_SRC: index.GREGEX_SRC,
    STRICT_RX_SRC: index.STRICT_RX_SRC,
    updateEntry,
    addEntry,
    deleteEntry,
    resetGlossary,
    exportGlossary,
    hasEdits,
    editCount,
  };

  return <GlossaryEditCtx.Provider value={value}>{children}</GlossaryEditCtx.Provider>;
}

// Read the current effective glossary + edit utilities. Returns null if
// the provider is not mounted (in which case callers should fall back to
// the static export).
export function useEditableGlossary() {
  return useContext(GlossaryEditCtx);
}
