import { useState, useEffect } from "react";
import { B } from "../data/brand";
import bmLogo from "../assets/Barasch_McGarry_Logo_2020_RGB.png";
import { MODULE6 } from "../data/module6Data";
import { initState, red, Ctx } from "../state";
import { useEditableContent } from "../hooks/useEditableContent";
import { usePersistedReducer } from "../hooks/usePersistedReducer";
import { KEYS } from "../hooks/useLocalStorage";
import StoryCard from "./StoryCard";
import ContentCard from "./ContentCard";
import QuizCard from "./QuizCard";
import MatchingCard from "./MatchingCard";
import ScenarioCard from "./ScenarioCard";
import AssessmentCard from "./AssessmentCard";
import CompletionCard from "./CompletionCard";
import DocumentReviewCard from "./cards/DocumentReviewCard";
import TranscriptCard from "./cards/TranscriptCard";
import GlossaryDrawer from "./GlossaryDrawer";

export default function Module6({ learner, moduleStartedAt, onHome, onSignIn, editMode, onExitEditMode, forceReview = false }) {
  const MODULE_ID = "module-6";
  const [s, d] = usePersistedReducer(red, initState, KEYS.module(MODULE_ID, learner?.email || "anonymous"));
  const [glossOpen, setGlossOpen] = useState(false);
  const [reviewMode, setReviewMode] = useState(forceReview);
  const toggleReviewMode = () => { if (!forceReview) setReviewMode(v => !v); };

  // Edit mode: merged cards + edit utilities
  const { cards: mergedCards, updateCard, resetModule, hasEdits, editCount } = useEditableContent(MODULE_ID, MODULE6.cards);

  // "Preview as learner" temporarily hides edit controls without exiting edit mode
  const [editPreview, setEditPreview] = useState(false);
  const effectiveEditMode   = editMode && !editPreview;
  const effectiveReviewMode = reviewMode && !editPreview;

  // Nav label inline editing
  const [editingNavId, setEditingNavId] = useState(null);
  const [navDraft, setNavDraft] = useState("");

  // Reset editPreview when editMode turns off
  useEffect(() => { if (!editMode) setEditPreview(false); }, [editMode]);

  useEffect(() => { window.scrollTo({top:0, behavior:"smooth"}); }, [s.cur]);

  const cards = mergedCards;
  const card  = cards[s.cur];
  const pct   = (s.cur / (cards.length - 1)) * 100;

  // Export merged card data as a drop-in src/data/module6Data.js replacement
  const exportDataFile = () => {
    const content = `// Auto-generated by Edit Mode — ${new Date().toISOString()}\n// Drop this file into src/data/ and rebuild to make edits permanent.\nexport const MODULE6 = ${JSON.stringify({ cards }, null, 2)};\n`;
    const blob = new Blob([content], { type: "text/javascript" });
    const url  = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url; a.download = "module6Data.js";
    a.click(); URL.revokeObjectURL(url);
  };

  const handleReset = () => {
    if (window.confirm("Reset all edits for Module 6? This will discard all in-browser changes and cannot be undone.")) {
      resetModule();
    }
  };

  let C;
  switch (card.type) {
    case "story":           C = <StoryCard data={card.data} cardId={card.id}/>; break;
    case "content":         C = <ContentCard data={card.data} cardId={card.id}/>; break;
    case "quiz":            C = <QuizCard data={card.data} cardId={card.id} cardIndex={s.cur}/>; break;
    case "matching":        C = <MatchingCard data={card.data} cardId={card.id}/>; break;
    case "scenario":        C = <ScenarioCard data={card.data} cardId={card.id}/>; break;
    case "assessment":      C = <AssessmentCard data={card.data} cardId={card.id}/>; break;
    case "completion":      C = <CompletionCard/>; break;
    case "document-review": C = <DocumentReviewCard data={card.data} cardId={card.id}/>; break;
    case "transcript":      C = <TranscriptCard data={card.data} cardId={card.id}/>; break;
    default:                C = null;
  }

  // Layout offsets
  const hasBanner  = effectiveReviewMode;
  const topOffset  = hasBanner ? 84 : 52;
  const hasToolbar = editMode && !editPreview;

  return (
    <Ctx.Provider value={{
      s, d, learner, moduleStartedAt,
      cards,
      moduleId:    "module-6-complex-cases",
      moduleTitle: "Module 6: Complex Cases",
      reviewMode:  effectiveReviewMode,
      toggleReviewMode,
      editMode:    effectiveEditMode,
      updateCard,
    }}>
      <div className="min-h-screen bg-brand-cream">

        {/* Progress bar */}
        <div className="fixed top-0 left-0 right-0 h-1 z-50 bg-brand-sand">
          <div className="h-full transition-all duration-500 bg-brand-blue" style={{width:`${pct}%`}} /* dynamic: computed progress width *//>
        </div>

        {/* Top nav */}
        <div className="fixed top-1 left-0 right-0 z-40 flex items-center justify-between px-5 py-2 bg-brand-hdr shadow-[0_2px_12px_rgba(0,0,0,0.2)]">
          <div className="flex items-center gap-4">
            <button onClick={onHome} className="bg-white rounded px-2 py-1 inline-flex items-center border-none cursor-pointer">
              <img src={bmLogo} alt="B&M" className="h-8"/>
            </button>
            <div className="w-px h-5 bg-white/15"/>
            <span className="text-xs text-white/50">Module 6: Complex Cases</span>
          </div>
          <div className="flex items-center gap-3">
            <button onClick={()=>setGlossOpen(true)}
              className="flex items-center gap-1.5 px-3 py-[5px] bg-white/[0.08] border border-white/15 rounded-md cursor-pointer text-white/70 text-xs font-semibold">
              <span className="text-sm">📖</span> Glossary
            </button>
            {!forceReview && (
              <button onClick={toggleReviewMode}
                className="flex items-center gap-1.5 px-3 py-[5px] rounded-md cursor-pointer text-xs font-semibold transition-all duration-150"
                style={reviewMode
                  ? {background:B.blue, color:"white", border:"1.5px solid "+B.blue}
                  : {background:"transparent", color:"rgba(255,255,255,0.6)", border:"1.5px solid rgba(255,255,255,0.25)"}}>
                <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/>
                </svg>
                {reviewMode ? "Reviewing" : "Review Mode"}
              </button>
            )}
            {forceReview && onSignIn && (
              <button onClick={onSignIn}
                className="flex items-center gap-1.5 px-3 py-[5px] rounded-md cursor-pointer text-xs font-semibold transition-all duration-150"
                style={{background: B.blue, color:"white", border:"1.5px solid "+B.blue}}>
                Sign in to complete →
              </button>
            )}
            {/* Edit mode badge + exit button */}
            {editMode && (
              <>
                <span
                  className="text-[10px] font-bold px-2 py-0.5 rounded-full"
                  style={{ background: "#fef3c7", color: "#92400e", border: "1px solid #fcd34d" }}
                >
                  {editPreview ? "Previewing" : "Editing"}
                </span>
                <button
                  onClick={() => { onExitEditMode(); setEditPreview(false); }}
                  className="flex items-center gap-1 px-3 py-[5px] rounded-md text-xs font-semibold cursor-pointer border-none"
                  style={{ background: "#fef3c7", color: "#92400e", border: "1.5px solid #fcd34d" }}
                >
                  Exit Edit Mode
                </button>
              </>
            )}
            {learner && <span className="text-xs text-white/35">{learner.name}</span>}
            <span className="text-xs text-white/40">Section {s.cur+1} of {cards.length}</span>
            <button onClick={onHome}
              className="px-3 py-1.5 rounded text-xs font-semibold cursor-pointer border-none"
              style={{ background: "rgba(255,255,255,0.08)", color: "rgba(255,255,255,0.6)", border: "1px solid rgba(255,255,255,0.15)" }}
            >← Return Home</button>
          </div>
        </div>

        {/* Review mode banner */}
        {effectiveReviewMode && (
          <div className="fixed left-0 right-0 z-40 flex items-center justify-center h-8 text-xs font-semibold" style={{top:52, background:"#dbeeff", color:"#1a6fa0", borderBottom:"1px solid #a8d4f5"}}>
            Review mode — all sections unlocked, questions skippable
          </div>
        )}

        <div className="flex" style={{marginTop: topOffset}} /* dynamic: offset for fixed nav + optional banner */>

          {/* Sidebar */}
          <div
            className="fixed left-0 overflow-y-auto z-30 py-5 w-60 bg-brand-side"
            style={{ top: topOffset, bottom: hasToolbar ? 48 : 0 }}
          >
            <div className="px-5 mb-3 text-xs font-bold tracking-widest text-white/25">SECTIONS</div>
            {cards.map((c, i) => {
              const act  = i === s.cur;
              const comp = s.done.has(i);
              const unlk = s.open.has(i) || effectiveReviewMode;
              const isEditingNav = effectiveEditMode && editingNavId === c.id;
              return (
                <div key={c.id}
                  onClick={()=>{ if (!isEditingNav) (unlk||comp)&&d({t:"GO",i}); }}
                  className="flex items-start gap-3 px-5 py-2"
                  style={{
                    borderLeft: `3px solid ${act ? B.blue : "transparent"}`,
                    background: act ? "rgba(255,255,255,0.06)" : "transparent",
                    opacity: unlk || comp ? 1 : 0.3,
                    cursor: unlk || comp ? "pointer" : "default",
                  }}>
                  <div className="w-5 h-5 rounded-full flex items-center justify-center font-bold shrink-0 mt-0.5 text-[9px]"
                    style={{
                      border: `2px solid ${comp ? B.ok : act ? B.blue : "rgba(255,255,255,0.2)"}`,
                      background: comp ? B.ok : "transparent",
                      color: comp ? "white" : act ? B.blue : "rgba(255,255,255,0.35)",
                    }}>
                    {comp ? "✓" : i+1}
                  </div>
                  <div className="flex items-center gap-1 min-w-0 flex-1">
                    {isEditingNav ? (
                      <input
                        className="text-xs bg-transparent border-b focus:outline-none flex-1 min-w-0"
                        style={{ borderColor: "#f59e0b", color: "white" }}
                        value={navDraft}
                        onChange={(e) => setNavDraft(e.target.value)}
                        onBlur={() => { updateCard(c.id, "nav", navDraft); setEditingNavId(null); }}
                        onKeyDown={(e) => {
                          if (e.key === "Enter") { updateCard(c.id, "nav", navDraft); setEditingNavId(null); }
                          if (e.key === "Escape") setEditingNavId(null);
                          e.stopPropagation();
                        }}
                        onClick={(e) => e.stopPropagation()}
                        autoFocus
                      />
                    ) : (
                      <>
                        <span className="text-xs truncate" style={{color: act ? "white" : "rgba(255,255,255,0.55)"}}>{c.nav}</span>
                        {effectiveEditMode && (
                          <span
                            onClick={(e) => { e.stopPropagation(); setNavDraft(c.nav); setEditingNavId(c.id); }}
                            className="shrink-0 cursor-pointer text-[11px] ml-1"
                            style={{ color: "rgba(251,191,36,0.5)" }}
                            onMouseEnter={(e) => (e.currentTarget.style.color = "rgba(251,191,36,1)")}
                            onMouseLeave={(e) => (e.currentTarget.style.color = "rgba(251,191,36,0.5)")}
                            title="Edit label"
                          >
                            ✎
                          </span>
                        )}
                        {effectiveReviewMode && act && (
                          <span className="text-[9px] font-bold px-1 rounded shrink-0 ml-1" style={{background:"rgba(0,155,223,0.3)", color:B.blue}}>Review</span>
                        )}
                      </>
                    )}
                  </div>
                </div>
              );
            })}
          </div>

          {/* Main content */}
          <div
            className="flex-1 py-8 px-10 ml-60 max-w-[840px]"
            style={{ paddingBottom: hasToolbar ? 80 : 32 }}
          >
            {C}
          </div>
        </div>

        {/* Fixed edit mode toolbar */}
        {editMode && !editPreview && (
          <div
            className="fixed bottom-0 left-0 right-0 z-40 flex items-center justify-between px-5 h-12"
            style={{ background: "#fef3c7", borderTop: "1px solid #fcd34d" }}
          >
            <div className="flex items-center gap-2 text-xs" style={{ color: "#92400e" }}>
              <span className="font-bold">Module 6</span>
              <span style={{ color: "#b45309" }}>
                {hasEdits ? `· ${editCount} field${editCount !== 1 ? "s" : ""} edited` : "· No edits yet"}
              </span>
            </div>
            <button
              onClick={() => setEditPreview(true)}
              className="flex items-center gap-1.5 px-3 py-1.5 rounded text-xs font-semibold cursor-pointer border-none"
              style={{ background: "white", border: "1.5px solid #fcd34d", color: "#92400e" }}
            >
              👁 Preview as learner
            </button>
            <div className="flex items-center gap-2">
              <button
                onClick={exportDataFile}
                className="flex items-center gap-1 px-3 py-1.5 rounded text-xs font-semibold cursor-pointer border-none"
                style={{ background: "white", border: "1.5px solid #fcd34d", color: "#92400e" }}
                title="Download module6Data.js to drop into src/data/"
              >
                ⬇ Export .js
              </button>
              <button
                onClick={handleReset}
                disabled={!hasEdits}
                className="flex items-center gap-1 px-3 py-1.5 rounded text-xs font-semibold cursor-pointer border-none disabled:opacity-40 disabled:cursor-default"
                style={{ background: hasEdits ? "#fee2e2" : "transparent", border: "1.5px solid #fca5a5", color: "#b91c1c" }}
              >
                ↺ Reset all
              </button>
            </div>
          </div>
        )}

        {/* "Exit learner preview" floating button */}
        {editMode && editPreview && (
          <div className="fixed bottom-6 left-1/2 z-50" style={{ transform: "translateX(-50%)" }}>
            <button
              onClick={() => setEditPreview(false)}
              className="flex items-center gap-2 px-5 py-2.5 rounded-full text-sm font-bold text-white shadow-xl cursor-pointer border-none"
              style={{ background: "#f59e0b" }}
            >
              ✏️ Exit Learner Preview
            </button>
          </div>
        )}

        <GlossaryDrawer open={glossOpen} onClose={()=>setGlossOpen(false)}/>
      </div>
    </Ctx.Provider>
  );
}
